# You can use it to add commands that run after login to macOS user session.
# 'start-at-login' needs to be 'true' for 'after-login-command' to work
# Available commands: https://nikitabobko.github.io/AeroSpace/commands
after-login-command = []

# You can use it to add commands that run after AeroSpace startup.
# 'after-startup-command' is run after 'after-login-command'
# Available commands : https://nikitabobko.github.io/AeroSpace/commands
after-startup-command = []

start-at-login = true

# Normalizations. See: https://nikitabobko.github.io/AeroSpace/guide#normalization
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

accordion-padding = 0
default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'
key-mapping.preset = 'qwerty'

[gaps]
inner.horizontal = 4
inner.vertical =   4
outer.left =       4
outer.bottom =     4
outer.top =        4
outer.right =      4

[mode.main.binding]

# All possible keys:
# - Letters.        a, b, c, ..., z
# - Numbers.        0, 1, 2, ..., 9
# - Keypad numbers. keypad0, keypad1, keypad2, ..., keypad9
# - F-keys.         f1, f2, ..., f20
# - Special keys.   minus, equal, period, comma, slash, backslash, quote, semicolon, backtick,
#                   leftSquareBracket, rightSquareBracket, space, enter, esc, backspace, tab
# - Keypad special. keypadClear, keypadDecimalMark, keypadDivide, keypadEnter, keypadEqual,
#                   keypadMinus, keypadMultiply, keypadPlus
# - Arrows.         left, down, up, right

# All possible modifiers: cmd, alt, ctrl, shift

# All possible commands: https://nikitabobko.github.io/AeroSpace/commands

alt-w = 'layout h_accordion' # 'layout tabbed' in i3
alt-e = 'layout tiles horizontal vertical' # 'layout toggle split' in i3
alt-shift-space = 'layout floating tiling' 

alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'

alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'

alt-cmd-j = 'workspace next'
alt-cmd-k = 'workspace prev'

# See: https://nikitabobko.github.io/AeroSpace/commands#resize
alt-shift-minus = 'resize smart -50'
alt-shift-equal = 'resize smart +50'

# See: https://nikitabobko.github.io/AeroSpace/commands#workspace
alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
alt-4 = 'workspace 4'
alt-5 = 'workspace 5'

alt-m = 'workspace main'
alt-b = 'workspace builtin'
alt-s = 'workspace secondary'

# See: https://nikitabobko.github.io/AeroSpace/commands#move-node-to-workspace
alt-shift-1 = 'move-node-to-workspace 1'
alt-shift-2 = 'move-node-to-workspace 2'
alt-shift-3 = 'move-node-to-workspace 3'
alt-shift-4 = 'move-node-to-workspace 4'
alt-shift-5 = 'move-node-to-workspace 5'

# See: https://nikitabobko.github.io/AeroSpace/commands#workspace-back-and-forth
alt-tab = 'workspace-back-and-forth'

# move windows between monitors by label
alt-shift-m = ['move-node-to-monitor main', 'focus-monitor main']
alt-shift-b = ['move-node-to-monitor built-in.*', 'focus-monitor built-in.*']
alt-shift-s = ['move-node-to-monitor PHL.*', 'focus-monitor PHL.*']

# move windows between monitors position
alt-n = ['move-node-to-monitor --wrap-around next', 'focus-monitor --wrap-around next']
alt-p = ['move-node-to-monitor --wrap-around prev', 'focus-monitor --wrap-around prev']

# move workspaces between monitors position
ctrl-shift-n = 'move-workspace-to-monitor --wrap-around next'
ctrl-shift-p = 'move-workspace-to-monitor --wrap-around prev'

alt-z = 'fullscreen'

# See: https://nikitabobko.github.io/AeroSpace/commands#mode
alt-shift-semicolon = 'mode service'
alt-shift-r = 'mode resize'
alt-shift-w = 'mode workspaces'

cmd-h = [] # Disable "hide application"
cmd-alt-h = [] # Disable "hide others"

[mode.service.binding]
esc = ['reload-config', 'mode main']
r = ['flatten-workspace-tree', 'mode main'] # reset layout
f = ['layout floating tiling', 'mode main'] # Toggle between floating and tiling layout
backspace = ['close-all-windows-but-current', 'mode main']

alt-shift-h = ['join-with left', 'mode main']
alt-shift-j = ['join-with down', 'mode main']
alt-shift-k = ['join-with up', 'mode main']
alt-shift-l = ['join-with right', 'mode main']

[mode.resize.binding]
h = 'resize width -50'
j = 'resize height +50'
k = 'resize height -50'
l = 'resize width +50'
e = [ 'balance-sizes', 'mode main' ]
enter = 'mode main'
esc = 'mode main'

[mode.workspaces.binding]
q = 'workspace 1'
w = 'workspace 2'
e = 'workspace 3'
r = 'workspace 4'
t = 'workspace 5'
b = 'workspace builtin'
m = 'workspace main'
s = 'workspace secondary'

ctrl-q = 'move-node-to-workspace 1'
ctrl-w = 'move-node-to-workspace 2'
ctrl-e = 'move-node-to-workspace 3'
ctrl-r = 'move-node-to-workspace 4'
ctrl-t = 'move-node-to-workspace 5'
ctrl-b = 'move-node-to-workspace builtin'
ctrl-m = 'move-node-to-workspace main'
ctrl-s = 'move-node-to-workspace secondary'

esc = 'mode main'

[workspace-to-monitor-force-assignment]
main = 'main'
builtin = 'built-in.*'
secondary = 'PHL.*'

[[on-window-detected]]
if.app-id = 'com.tinyspeck.slackmacgap'
run = ['move-node-to-workspace secondary']

[[on-window-detected]]
if.app-id = 'com.spotify.client'
run = ['move-node-to-workspace builtin']
