import = [
	"~/.config/alacritty/themes/themes/github_dark_high_contrast.toml"
]
live_config_reload = true

[env]
TERM = "xterm-256color"

[shell]
program = "/bin/zsh"
args = ["-l", "-c", "tmux attach || tmux"]

[font]
size = 15
normal = { family = "JetBrainsMono Nerd Font" }

[window]
option_as_alt = "Both"
decorations = "Buttonless"
dynamic_padding = true
